### ISSUE TITLE
tRNAscan error##permission denied

### ISSUE THREAD

**Issue by ashaneev** [UCSC-LoweLab/tRNAscan-SE#1]
Hii...

I've  installed tRNAscan-SE-2.0 on my PC (ubuntu 14.04).But, when i tried with  '-h' command shows the following error messages.
Could you please clarify this?

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/tRNAscan-SE-2.0$ sudo make
[sudo] password for home: 
make  all-am
make[1]: Entering directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'
sed -e 's,\@bindir\@,/usr/local/bin,g' -e 's,\@libdir\@,/usr/local/lib,g' -e 's,[@]PERL[@],/usr/bin/perl,g' -e 's,\@INFERNAL\@,,g'  < ./src/sstofa.in > bin/sstofa
chmod +x bin/sstofa
sed -e 's,\@bindir\@,/usr/local/bin,g' -e 's,\@libdir\@,/usr/local/lib,g' -e 's,[@]PERL[@],/usr/bin/perl,g' -e 's,\@INFERNAL\@,,g'  < ./src/fasta2gsi.in > bin/fasta2gsi
chmod +x bin/fasta2gsi
sed -e 's,\@bindir\@,/usr/local/bin,g' -e 's,\@libdir\@,/usr/local/lib,g' -e 's,[@]PERL[@],/usr/bin/perl,g' -e 's,\@INFERNAL\@,,g'  < ./EukHighConfidenceFilter.in > bin/EukHighConfidenceFilter
chmod +x bin/EukHighConfidenceFilter
sed -e 's,\@bindir\@,/usr/local/bin,g' -e 's,\@libdir\@,/usr/local/lib,g' -e 's,[@]PERL[@],/usr/bin/perl,g' -e 's,\@INFERNAL\@,,g'  < ./tRNAscan-SE.src > tRNAscan-SE
chmod +x tRNAscan-SE
sed -e 's,\@bindir\@,/usr/local/bin,g' -e 's,\@libdir\@,/usr/local/lib,g' -e 's,[@]PERL[@],/usr/bin/perl,g' -e 's,\@INFERNAL\@,,g'  < ./tRNAscan-SE.conf.src > tRNAscan-SE.conf
chmod +x tRNAscan-SE.conf
make[1]: Leaving directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/tRNAscan-SE-2.0$ sudo make install
make[1]: Entering directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c bin/eufindtRNA bin/trnascan-1.4 bin/covels-SE bin/coves-SE '/usr/local/bin'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
 /usr/bin/install -c bin/sstofa bin/fasta2gsi bin/EukHighConfidenceFilter tRNAscan-SE tRNAscan-SE.conf '/usr/local/bin'
test -z "/usr/local/include" || /bin/mkdir -p "/usr/local/include"
 /usr/bin/install -c -m 644 ./src/dbmalloc.h ./src/eufind_const.h ./src/funcs.h ./src/gnuregex.h ./src/maspar.h ./src/prior.h ./src/sqfuncs.h ./src/squid.h ./src/structs.h ./src/version.h '/usr/local/include'
make  install-data-hook
make[2]: Entering directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'
chmod u+w /usr/local
test -d /usr/local/lib || mkdir /usr/local/lib
chmod u+w /usr/local/lib
test -d /usr/local/lib/tRNAscan-SE || mkdir /usr/local/lib/tRNAscan-SE
cp -rf ./lib/* /usr/local/lib/tRNAscan-SE 
make[2]: Leaving directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'
make[1]: Leaving directory `/home/Documents/UN_GEnome/tRNAscan-SE-2.0'

home@home-Lenovo-H30-50:~/Documents/UN_GEnome/tRNAscan-SE-2.0$ tRNAscan-SE -h
Can't locate tRNAscanSE/Configuration.pm:   Permission denied at /usr/local/bin/tRNAscan-SE line 23.
BEGIN failed--compilation aborted at /usr/local/bin/tRNAscan-SE line 23.

**Comment by patriciaplchan** [comment]
You can use the following command to fix the problem:
sudo chown o+x /usr/local/lib/tRNAscan-SE/tRNAscanSE
