### ISSUE TITLE
need help: Unable to open /home/cz/fasta/h.faa for reading.  Aborting program.

### ISSUE THREAD

**Issue by yuanzou865** [UCSC-LoweLab/tRNAscan-SE#11]
hello,when I use it under ubuntu：
(base) cz@DESKTOP-B4R0NCF:~$ tRNAscan-SE -o tRNA.out -f tRNA.ss -m tRNA.stats  /home/cz/fasta/h.fasta
It has the following problems：
Status: Phase I: Searching for tRNAs with HMM-enabled Infernal
Unable to open /home/cz/fasta/h.faa for reading.  Aborting program.

**Comment by patriciaplchan** [comment]
The error means that your input sequence file is not readable. Please that it is in the correct FASTA file format with UNIX style line ending and the readable permission is set.
