### ISSUE TITLE
[Need Help] FATAL: Unable to open output file

### ISSUE THREAD

**Issue by hjgwak** [UCSC-LoweLab/tRNAscan-SE#12]
Hello
I'm interested in using tRNAscan-SE in my project.
I was surprised by the performance of tRNAscan-SE against the reference genome.
The accuracy of this program is what I needed.

Thus, I tried to apply tRNAscan-SE for PacBio long-read data.
I wanted to find tRNA from 16S-23S sequencing reads.
However, tRNAscan-SE died after printing the following message 
"FATAL: Unable to open output file"

For small data (about < 10M), it worked well.
However, in my case, as soon as the number of tRNA sequences exceeds 1012, the above error occurs.

I used the following comment for running tRNAscan-SE
`tRNAscan-SE -B -q -Q -o sample.out -s sample.iso -j sample.gff --thread 10 input.fasta`

How can I handle this issue?
I hope for your help.

Thank you.

**Comment by patriciaplchan** [comment]
tRNAscan-SE was not designed or tested to be used with sequencing reads of any platform. Therefore, we are not able to provide much information about your issue. If it works well with small data set, you may want to split your data into multiple parts and run tRNAscan-SE on them separately.

**Comment by hjgwak** [comment]
Thanks for your answer.
I solved that issue by splitting my sample into multiple files
