### ISSUE TITLE
sprinzl position alignment files missing

### ISSUE THREAD

**Issue by lpryszcz** [UCSC-LoweLab/tRNAscan-SE#14]
Hi, I'd like to get sprinzl position from tRNAscan-SE. Where can I get the files needed for that `*_sprinzl.cm`?

Relevant part of conf file that is commented out by default:
```bash
# to be used for sprinzl position alignment
# sprinzl_cm_dir: {lib_dir}/models
# sprinzl_cm.euk: {sprinzl_cm_dir}/euk_sprinzl.cm
# sprinzl_cm.arch: {sprinzl_cm_dir}/arch_sprinzl.cm
# sprinzl_cm.bact: {sprinzl_cm_dir}/bact_sprinzl.cm
```

**Comment by patriciaplchan** [comment]
Those special covariance models are for a different purpose and not currently used in tRNAscan-SE. That's why they have been commented out in the configuration file. tRNAscan-SE currently does not output the Sprinzl positions for individual tRNA genes.
