### ISSUE TITLE
No clear tutorial for the installation and using command line 

### ISSUE THREAD

**Issue by B-1991-ing** [UCSC-LoweLab/tRNAscan-SE#15]
Dear tRNAscan-SE development team,

I downloaded the "**trnascan-se-2.0.12.tar**" from the web link --- "http://trna.ucsc.edu/tRNAscan-SE/", but not sure how to **install** on my linux directory correctly and how to **use** it through linux command line ?

Could you give me a hint?

Thank you very much.

Best,

Bing

**Comment by patriciaplchan** [comment]
Please read the INSTALL file in the downloaded tRNAscan-SE on how to install the software. 

The following paper provides information on how to use the software.
Chan, P.P. and Lowe, T. M. (2019) [tRNAscan-SE: Searching for tRNA Genes in Genomic Sequences.](https://www.ncbi.nlm.nih.gov/pubmed/31020551) Methods Mol Biol. 1962:1-14.

**Comment by B-1991-ing** [comment]
Thank you very much for your suggestion.

The HPC admin installed it publicly on our HPC platform through 
**tar -xvf tRNAscan-SE-2.0.12.tar.gz
./configure #
make && make install**

Then, I ran the following command line on 330 prokaryotic genomes.
 **tRNAscan-SE final.fa -o final.out -f final.ss -s final.iso  -m final.stats -b final.bed -c tRNAscan-SE.conf**

But, how long would it take to finish the scanning on 330 assembled genomes normally?

**Comment by patriciaplchan** [comment]
The required time will depend on the speed of your computing system and the number of processing cores used for the run.  It took our lab's system less 1 minute to scan a prokaryotic genome. Table 3 in our paper below provides the benchmark.

Chan, P.P., Lin, B.Y., Mak, A.J., and Lowe, T.M. (2021) [tRNAscan-SE 2.0: Improved Detection and Functional Classification of Transfer RNA Genes.](https://doi.org/10.1093/nar/gkab688) Nucl. Acids Res. 49:9077–9096.

**Comment by B-1991-ing** [comment]
I ran on the thinnode as below,
qsub -W group_list=env_10000 -A env_10000 -l nodes=1:ppn=32:thinnode,walltime=240:00:00 MAGtRNA.sh
Already 330 minutes passed with 32 HPC cores, 192 GB memory consuming. My genome size is around 1-5 MB.

**Comment by patriciaplchan** [comment]
As every computing system including hardcore and software configuration is different, I would not be able to provide any estimation of the run time on the system you are using. I can only provide reference to the systems in our lab. If you are interested in obtaining run time estimation of your computing environment, I would suggest that you contact your local support staff and provide the benchmark in our paper as reference.

**Comment by B-1991-ing** [comment]
Okay, thank you very much. If it runs more than one week, I will email our HPC admin.

**Comment by B-1991-ing** [comment]
Running the command line below gave me one error 

**Command line**
/services/tools/trnascan-se/2.0.12/bin/tRNAscan-SE final.fa -o final.out -f final.ss -s final.iso -m final.stats -c /services/tools/trnascan-se/2.0.12/bin/tRNAscan-SE.conf

**Error**
FATAL: Unable to find /services/tools/trnascan-se/2.0.12/bin/cmsearch executable

What does it mean?

**Comment by patriciaplchan** [comment]
As stated in the INSTALL file of the tRNAscan-SE package and the first publication I mentioned before, Infernal is a required dependency and has to be installed in the same directory as tRNAscan-SE. Please read the documentation.

**Comment by B-1991-ing** [comment]
But the tRNAscan-SE and  Infernal were already installed under two different directories by the HPC admin.

**Comment by patriciaplchan** [comment]
As mentioned above, Infernal has to be installed in the SAME directory as tRNAscan-SE. If it is in a different directory, you will need to update the file path for the value of "infernal_dir" in tRNAscan-SE.conf.

**Comment by B-1991-ing** [comment]
I can't update the tRNAscan-SE.conf myself.  Can I specify the value of "infernal_dir" in the command line?

**Comment by patriciaplchan** [comment]
No. You will have to update tRNAscan-SE.conf or reinstall infernal in the SAME directory as tRNAscan-SE.

**Comment by darked89** [comment]
One can also install tRNAscan-SE with included infernal using conda: https://anaconda.org/bioconda/trnascan-se

**Comment by B-1991-ing** [comment]
Thank you for your reply. 

The HPC admin installed the **cmsearch** under the directory ---  /services/tools/trnascan-se/2.0.12/bin/ finally.
