### ISSUE TITLE
plant mitochondria model

### ISSUE THREAD

**Issue by zmz1988** [UCSC-LoweLab/tRNAscan-SE#17]
Hello, thank you so much for providing this easy-to-use tool! I read in the paper that now the mitochondria tRNA search model is only available for mammals and vertebrates. May I ask how could we search for the plant mitochondria tRNA sequences from genome sequence? If the study species is a model species, could we have the possibility to feed in the model species tRNA sequence to scan? Thanks!

**Comment by patriciaplchan** [comment]
You can use the option for organellar tRNAs to search plant mitochondrial genomes. In the standalone software, the option is -O. For using the web server version (http://trna.ucsc.edu/tRNAscan-SE/), set the sequence source as Other mitochondrial.

**Comment by zmz1988** [comment]
Thanks! That's very helpful!
