### ISSUE TITLE
Error: substr outside of string tRNAscan-SE/tRNAscanSE/Utils.pm line 117, <__ANONIO__> line 58276.

### ISSUE THREAD

**Issue by rhysnewell** [UCSC-LoweLab/tRNAscan-SE#20]
Hi Patricia,

Just wanted to flag this odd error I've been receiving. So far it has only occurred on one genome, every other genome runs through perfectly fine. I've attached the genome so you can try and see if you can reproduce the error. The command I used was as follows:
```
tRNAscan-SE --thread 8 -o trnascan_test -j transcan_test.gff -B test_genome.fna
```

I've checked the file multiple times and cannot spot any strange formatting that might cause this issue. Additionally, other programs like EGGNOG-mapper and barrnap can parse this file with no issue.

Any help would be appreciated!
Cheers,
Rhys
[test_genome.fna.zip](https://github.com/UCSC-LoweLab/tRNAscan-SE/files/11013499/test_genome.fna.zip)

**Comment by patriciaplchan** [comment]
Hi Rhys,

Your file uses WIndows line ending (CRLF) that is not supported by tRNAscan-SE. Please convert it to UNIX line endling (LF) and try again.

best,
Patricia
