### ISSUE TITLE
Was the organelle model made based only on plastid tRNAs?

### ISSUE THREAD

**Issue by shelkmike** [UCSC-LoweLab/tRNAscan-SE#21]
In tRNAscan-SE 2, the option "-M" means "search for mitochondrial tRNAs", while the option "-O" means "search for other organellar tRNAs".

I wonder, what "other organellar tRNAs" mean. Aren't they just plastid tRNAs?

**Comment by patriciaplchan** [comment]
The -M option currently only supports mitochondrial tRNAs in vertebrates. For organellar tRNAs of other types or organisms, please try out the -O option. Plastid tRNAs in plants can usually be detected by the default mode.
