### ISSUE TITLE
Latest version in Bioconda

### ISSUE THREAD

**Issue by llk578496** [UCSC-LoweLab/tRNAscan-SE#22]
Hello @patriciaplchan,

We were wondering if it is possible to obtain the latest version, `v2.0.12`, since the latest version available in bioconda is `v2.0.11`.

Thank you for your help!

Best regards,
Eddie

**Comment by patriciaplchan** [comment]
v2.0.12 is available in bioconda.

**Comment by llk578496** [comment]
Thanks a lot!
