### ISSUE TITLE
Incompatibility with infernal although infernal 1.1.4 installed

### ISSUE THREAD

**Issue by johnne** [UCSC-LoweLab/tRNAscan-SE#23]
Hi!
I'm getting an incompatibility error when running tRNAscan-SE version 2.0.11:

```bash
tRNAscan-SE -G -o genomes/annotations/dram/intermediate_files/MAG4/working_dir/MAG4/tmp/raw_trnas.txt --thread 1 genomes/annotations/dram/intermediate_files/MAG4/working_dir/MAG4/scaffolds.annotated.fa
```

gives:

```
FATAL: /crex/proj/snic2020-5-486/nobackup/SMS-23-6668-micegut/resources/conda_envs/dram/bin/cmsearch is incompatible with tRNAscan-SE. Please install Infernal version 1.1.2 or above.
```

although when running with the cmsearch executable located by tRNAscan-SE it reports infernal version 1.1.4:

```bash
$ cmsearch -h | grep INFERNAL
# INFERNAL 1.1.4 (Dec 2020)
```

I tested the perl code used to check the cmsearch version and it reports that the variable `$version` is 0 so to me it looks like it isn't able to match the output from `cmsearch -h` properly. I don't know if this is some perl incompatibility at the root of it? `which perl` reports I'm running v5.32.1.

**Comment by patriciaplchan** [comment]
The default installation of tRNAscan-SE expects the binaries of Infernal are located in the same directory as tRNAscan-SE. I suspect that you got the error because Infernal was installed in a different directory. You can solve this problem by one of these options:
1) add symbolic links of the Infernal binaries to where tRNAscan-SE was installed
2) update tRNAscan-SE.conf - the configuration file of tRNAscan-SE located in the same bin directory as tRNAscan-SE
Inside the file, change the value of "infernal_dir"  to the file path where Infernal is located.

**Comment by johnne** [comment]
Thanks for the reply.
No both `cmsearch` and `tRNAscan-SE` are in the same folder `/crex/proj/snic2020-5-486/nobackup/SMS-23-6668-micegut/resources/conda_envs/dram/bin`. This is also in the config you mention, here are the first few lines:

```
# tRNAscan-SE 2.0 
# Configuration File

# default paths
bin_dir: /crex/proj/snic2020-5-486/nobackup/SMS-23-6668-micegut/resources/conda_envs/dram/bin
lib_dir: /crex/proj/snic2020-5-486/nobackup/SMS-23-6668-micegut/resources/conda_envs/dram/lib/tRNAscan-SE
infernal_dir: {bin_dir}
```

**Comment by patriciaplchan** [comment]
How about cmscan? Do you have that in the same directory?

**Comment by johnne** [comment]
Yes,

**Comment by patriciaplchan** [comment]
Unfortunately I am not able to reproduce the problem you are experiencing. I am wondering if it has to do with how your environment parses regular expression. I changed the code in the attached gzipped version below. You can try to replace the original CM.pm in lib/tRNAscan-SE/tRNAscanSE with this one to see if it will work.

[CM.pm.gz](https://github.com/UCSC-LoweLab/tRNAscan-SE/files/11484463/CM.pm.gz)

**Comment by johnne** [comment]
Yes, that works! As you say probably something with regex matching.

Thank you very much for your help!
