### ISSUE TITLE
Using config file with tRNAscan-SE from conda

### ISSUE THREAD

**Issue by julie-tooi** [UCSC-LoweLab/tRNAscan-SE#29]
Hello!
Thank you for your work and great tool!

I have a question about config file usage:

I installed the tRNAscan-SE (v2.0.9) with conda 
It looks like I don't have the original file tRNAscan-SE.conf (at least in env folder)

I tried to copy the config file from tRNAscan-SE repo and use ```-c``` command to provide tRNAscan-SE.conf.src

```
tRNAscan-SE -c tRNAscan-SE.conf.src -o test ~/test.fasta
``` 

The annotation failed with this message:
```
/tscan9759.fpass for writing.  Aborting program.
``` 

Do you have any ideas on how to solve this?

Many thanks,
Julie

**Comment by patriciaplchan** [comment]
tRNAscan-SE.conf should be installed in the same directory as tRNAscan-SE executable. Please look for it. 

During the installation, new values are inserted into tRNAscan-SE.conf.src for creating tRNAscan-SE.conf. Therefore, directly using tRNAscan-SE.conf.src will not work.

**Comment by julie-tooi** [comment]
Thank you for the answer! 

I found the tRNAscan-SE.conf ```miniconda3/envs/trnascan_env/bin``` folder, but not in libs :D 

Now everything works, thanks!
