### ISSUE TITLE
make: unrecognized option '--prefix='

### ISSUE THREAD

**Issue by Tdanis** [UCSC-LoweLab/tRNAscan-SE#3]
Hello I am trying to install tRNAscan-SE-2.0 to my acoount, as an HPC user and after using the option 
--prefix (make install --prefix=....), the output error is,

make: unrecognized option '--prefix='
Usage: make [options] [target] ...
.....

Could you help me please?
Thank you

**Comment by patriciaplchan** [comment]
To specify an installation location, --prefix option should be used with the configure command before running make. For more information, please check out the INSTALL file that comes with the tRNAscan-SE package.

best,
Patricia

**Comment by Tdanis** [comment]
Sorry for this, now I am taking this error

/usr/bin/install: 'bin/eufindtRNA' and '/home1/tdanis/Software/tools/tRNAscan-SE-2.0/bin/eufindtRNA' are the same file
/usr/bin/install: 'bin/trnascan-1.4' and '/home1/tdanis/Software/tools/tRNAscan-SE-2.0/bin/trnascan-1.4' are the same file
/usr/bin/install: 'bin/covels-SE' and '/home1/tdanis/Software/tools/tRNAscan-SE-2.0/bin/covels-SE' are the same file
/usr/bin/install: 'bin/coves-SE' and '/home1/tdanis/Software/tools/tRNAscan-SE-2.0/bin/coves-SE' are the same file
Makefile:318: recipe for target 'install-binPROGRAMS' failed
make[1]: *** [install-binPROGRAMS] Error 1
make[1]: Leaving directory '/home1/tdanis/Software/tools/tRNAscan-SE-2.0'
Makefile:825: recipe for target 'install-am' failed
make: *** [install-am] Error 2

**Comment by patriciaplchan** [comment]
Did you try to do the installation multiple times in different ways? It looks like that previous attempts have installed some of the programs and cause conflicts when installing them again. I would suggest that you run "make clean" to clean up the current installation. Look at directories that may have some of the programs installed previously and remove them. Then restart from the beginning by running configure.

best,
Patricia

**Comment by Tdanis** [comment]
Hello Patricia, I have the same issues again, after following all your comments. I want to remind you that I do not have sudo previleges.

Thank you

**Comment by patriciaplchan** [comment]
Do you specific the directory for --prefix the same one as where the decompressed installation package is located? If you are, it will have a conflict because you will be trying to overwrite the same binaries with themselves. You will need to specific a different directory for --prefix.

best,
Patricia

**Comment by Tdanis** [comment]
It is ok now.

Thank you very much

**Comment by jythonkip** [comment]
You've copy-pasted the command from a webpage and, if you look closely, you've got a funny character instead of one of the dashes in --prefix.

Just type it in manually :)
