### ISSUE TITLE
Undet and NNN Anticodon in alternative models

### ISSUE THREAD

**Issue by ishengtsai** [UCSC-LoweLab/tRNAscan-SE#33]
Hi,

I have a set of stk files downloaded from a paper, and recompiled into cm files using cmbuild and cmcalibrate. However, when using these files to annotate tRNA using tRNAscan-SE , all the predictions show Undet(ermined) and unknown Anticodons. I was wondering if you could suggest on what I could do next please?

Command to build cm files (from actual cm file):
COM      [1] cmbuild trnA.cm trnA.stk
COM      [2] cmcalibrate --cpu 36 trnA.cm

tRNAscan-SE.conf modification:
alt_cm_dir: paper.cm
alt_cm.Ala: {alt_cm_dir}/trnA.cm
alt_cm.Arg: {alt_cm_dir}/trnR.cm

Command:
tRNAscan-SE --output tRNAscan_O2  -U  ref.fa

Output:
Sequence                tRNA    Bounds  tRNA    Anti    Intron Bounds   Inf
Name            tRNA #  Begin   End     Type    Codon   Begin   End     Score   Note
--------        ------  -----   ------  ----    -----   -----   ----    ------  ------
B1_4.mito       1       4598    4652    Undet   NNN     0       0       32.0
B1_4.mito       2       19475   19433   Undet   NNN     0       0       23.4
B1_4.mito       3       19417   19374   Undet   NNN     0       0       20.1
B1_4.mito       4       2083    2045    Undet   NNN     0       0       22.3

Any help would be appreciated. Thank you!

**Comment by patriciaplchan** [comment]
The results depend on what data were used to train the covariance models and what input sequences you are scanning. The current version of tRNAscan-SE was not designed to detect mitochondrial tRNA genes with highly degenerative features such as missing both D-arm and T-arm. If those are the tRNAs you are looking for, it may not be determine to the location of the anticodon correctly. You may have to manually check the predicted secondary structure and make adjustments to the annotations accordingly.

**Comment by ishengtsai** [comment]
Hi Patricia,

Many thanks for the comments. They are indeed lacking either D-arm or T-arm, or both. In these cases, we will align the candidate regions, determine the boundary of these tRNAs and make these adjustments. Hopefully by rebuilding these covariance models and iterating the process we can make better predictions.
