### ISSUE TITLE
mature tRNA & precursor tRNAs

### ISSUE THREAD

**Issue by cement-head** [UCSC-LoweLab/tRNAscan-SE#34]
Hello,

  Is there a configuration where tRNAscan-SE2 will give both the mature tRNAs (FASTA) and the precursor, or pre-tRNA (FASTA) files?

TIA

**Comment by patriciaplchan** [comment]
The tool currently only provides sequences of tRNA genes (i.e. may include introns) in fasta files. We will add this as a new feature request.
