### ISSUE TITLE
acquire all reference tRNA sequences of Homo sapiens

### ISSUE THREAD

**Issue by SHIPTOWN** [UCSC-LoweLab/tRNAscan-SE#40]
Hi

l am trying to detect specific tRNA‘s abundance in my samples,

but some tRNA sequences are not provided in GtRNAdb, such as Phe-AAA, His-ATG...

So l try to use the human reference genome GRCh38 to detect all annotated tRNAs with tRNAscan‐SE [v2.0], 

but the input FASTA is too big！Would you provide all reference tRNA sequences of Homo sapiens genome (maybe GtRNAdb is inadequate)

THANKS !!!

**Comment by patriciaplchan** [comment]
tRNA genes do not exist for every single anticodon. This is universal for all organisms. Please check out the [FAQ of GtRNAdb](https://gtrnadb.ucsc.edu/faq.html) for further information.
