### ISSUE TITLE
Conda seemingly installs version 1.4 

### ISSUE THREAD

**Issue by mstagliamonte** [UCSC-LoweLab/tRNAscan-SE#41]
Dear Authors,

Since I am working on a computer cluster, I have tried to install tRNAscan-SE using conda; unfortunately, it seems to install version 1.4 of the program. I have also tried specifying the version I want:

conda install bioconda::trnascan-se=2.0.12

But I still get the 1.4:

```
$trnascan-1.4 -h
trnascan: scan a sequence for tRNAs
  version 1.4 (Feb 96)

....

```

Trying to update it just got me the message that all requested packages are already installed.
Can you please advice?

Best,
Max

**Comment by patriciaplchan** [comment]
To execute tRNAscan-SE, you need to type 'tRNAscan-SE" at the command prompt, not trnascan-1.4. trnascan-1.4 is a tool used internally by tRNAscan-SE which you should not execute on its own in most of the cases.

**Comment by mstagliamonte** [comment]
Thank you for your help, I appreciate it.

Best,
Max
