### ISSUE TITLE
EukHighConfidenceFilter fails to write output file

### ISSUE THREAD

**Issue by sanaek** [UCSC-LoweLab/tRNAscan-SE#8]
Hello, I'm running EukHighConfidenceFilter to trnaScan-SE detail output but fails to write its output (either on my personal computer and on cluster server). The command I used is the following:

`EukHighConfidenceFilter -i forficula.consensus.v1sta.masked.out -s trna.strc.for.tbl -p euk.conf.for -o /eukconfi`

and the final message of the program:

`Status: Writing output file /eukconfi/euk.conf.for.out
Fail to open /eukconfi/euk.conf.for.out`

Is this related to writing permissions? Im sorry if this is too basic, Im new to bioinformatics. 

Thank you

**Comment by patriciaplchan** [comment]
Please check if the output directory /eukconfi is already existed. If not, you will have to create it before running the tool.

**Comment by sanaek** [comment]
I created the folder before running `EukHighConfidenceFilter` and the error is the one above, I tried not creating it also, but the issue is the same

**Comment by patriciaplchan** [comment]
Do you receive other error messages before the one you listed? Can you send all the output messages when running the tool?

**Comment by sanaek** [comment]
Hello

`EukHighConfidenceFilter -i forficula.consensus.v1sta.masked.out -s trna.strc.for.tbl -p euk.conf.for -o /eukconfi
mkdir: /eukconfi: Read-only file system
Status: Filtering pseudogenes
Use of uninitialized value $header{"hmm_score"} in array element at /Users/sanae/anaconda3/envs/trna/bin/EukHighConfidenceFilter line 381, <FILE_IN> line 7.
.....
Argument "scaffold_36448" isn't numeric in numeric lt (<) at /Users/sanae/anaconda3/envs/trna/bin/EukHighConfidenceFilter line 457.
Status: Tertiary filtering
Status: Writing output file /eukconfi/euk.conf.for.out
Fail to open /eukconfi/euk.conf.for.out`

Thats about it (... indicate the other lines running)

Thank you!

**Comment by patriciaplchan** [comment]
It looks like you have two problems. 1) You have a read-only file system error when creating directory /eukconfi. This means that you have no access right to create the directory. You will have to change access permission or use another output directory. 2) The tool was not able to find the hmm_score column in the tRNAscan-SE output file. When running tRNAscan-SE, please make sure to include "-H --detail" as options. If you did not do that, please run it again before running EukHighConfidenceFilter.

**Comment by sanaek** [comment]
Great, thank you for you help!
